version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-network

  backend:  
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Frontend.Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - 5173:80
    networks:
      - app-network      

volumes:
  db-data:

networks:
  app-network: